baseURL = "http://voxelate.net/"
languageCode = "id"
title = "VOXELATE"
theme = "seminyak"

[params]
  theme_color = "#66ccff"
  color_palette = "blue"
  background_image_url = "static/css/DSC03517.png"
  referrer_policy = "same-origin"
  google_fonts = "Oswald|Raleway"
