baseURL = "http://voxelate.net/"
languageCode = "id"
title = "VOXELATE"
theme = "seminyak"

[params]
  theme_color = "#7e7ee3"
  color_palette = "purple"
  background_image_url = "images/bgimgCOsmallfastload.jpg"
  referrer_policy = "same-origin"
  google_fonts = "Oswald|Raleway"
